apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: pgsql-grafana-datasource
spec:
  datasources:
    - name: PostgreSQL
      type: postgres
      typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
      access: proxy
      url: postgresql:5432
      password: HT@1202k
      user: dbadmin
      database: pgdb
      basicAuth: false
      isDefault: true
      jsonData:
        postgresVersion: 903
        sslmode: disable
      readOnly: false
  name: grafana-pgsql-datasource.yaml